# Generated by Django 6.0.7 on 2026-08-01 07:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icd_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dose', models.CharField(blank=True, max_length=50, null=True)),
                ('regimen', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('admission_reason', 'Admission Reason'), ('clinic_type', 'Clinic Type'), ('marital_status', 'Marital Status'), ('current_status', 'Current Status'), ('complication_status', 'Complication Status'), ('vaccine_name', 'Vaccine Name'), ('special_blood_type', 'Special Blood Type'), ('growth', 'Growth')], max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('common_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('ethnicity', models.CharField(blank=True, choices=[('Sinhalese', 'Sinhalese'), ('Tamil', 'Tamil'), ('SriLankanMoor', 'Sri Lankan Moor'), ('Burger', 'Burger'), ('Other', 'Other')], default='Sinhalese', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('nic_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client_photos/')),
                ('guardian_name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_contact_number_1', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_contact_number_2', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('HB_level_at_diagnosis', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('date_first_transfused', models.DateField(blank=True, null=True)),
                ('date_iron_chelation_started', models.DateField(blank=True, null=True)),
                ('transfusion_regimen', models.CharField(blank=True, max_length=200, null=True)),
                ('allergic_history', models.TextField(blank=True, null=True)),
                ('special_note', models.TextField(blank=True, null=True)),
                ('marital_status', models.ForeignKey(blank=True, limit_choices_to={'category': 'marital_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_marital_status', to='clients.choice')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.diagnosistype')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_admission', models.DateField()),
                ('date_of_discharge', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reason_for_admission', models.ForeignKey(limit_choices_to={'category': 'admission_reason'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.choice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_admissions', to='clients.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientDeath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_death', models.DateField()),
                ('cause_of_death', models.TextField(blank=True, null=True)),
                ('postmortem_findings', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death_record', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_visit', models.DateField()),
                ('problem', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('referral', models.CharField(blank=True, max_length=200, null=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_visits', to='clients.client')),
                ('clinic_type', models.ForeignKey(limit_choices_to={'category': 'clinic_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.choice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_complications', to='clients.client')),
                ('status', models.ForeignKey(limit_choices_to={'category': 'complication_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.choice')),
                ('complication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.complicationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescribed', models.DateField()),
                ('dose', models.CharField(max_length=50)),
                ('regimen', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('indication', models.CharField(blank=True, max_length=200, null=True)),
                ('prescribed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='clients.client')),
                ('drug_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.drugname')),
            ],
        ),
        migrations.CreateModel(
            name='DS_Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_divisions', to='clients.district')),
            ],
            options={
                'verbose_name': 'DS Division',
                'verbose_name_plural': 'DS Divisions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='ds_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.ds_division'),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sibling', 'Sibling'), ('Other', 'Other')], default='Other', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('is_carrier', models.BooleanField(default=False)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='clients.client')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.diagnosistype')),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_family_member', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_measured', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='clients.client')),
                ('type', models.ForeignKey(limit_choices_to={'category': 'growth'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.choice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_done', models.DateField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('text_value', models.CharField(blank=True, max_length=100, null=True)),
                ('laboratory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_investigations', to='clients.client')),
                ('investigation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.investigationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='clients.province'),
        ),
        migrations.CreateModel(
            name='ThalassemiaUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ds_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.ds_division')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transfer', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_record', to='clients.client')),
                ('transferred_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_clients', to='clients.thalassemiaunit')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCareUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('SHARED', 'Shared'), ('REFERRAL', 'Referral')], default='PRIMARY', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_links', to='clients.client')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='clients.thalassemiaunit')),
            ],
            options={
                'ordering': ['client', '-is_active', 'role', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='care_units',
            field=models.ManyToManyField(blank=True, related_name='care_clients', through='clients.ClientCareUnit', to='clients.thalassemiaunit'),
        ),
        migrations.CreateModel(
            name='Transfusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_transfusion', models.DateField()),
                ('pre_HB_level', models.DecimalField(blank=True, decimal_places=1, default=9.0, max_digits=4, null=True)),
                ('post_HB_level', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('WBC_count', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('platelet_count', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('amount_of_blood', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('next_date_given', models.DateField(blank=True, null=True)),
                ('reaction', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_transfusions', to='clients.admission')),
                ('special_type', models.ForeignKey(blank=True, limit_choices_to={'category': 'special_blood_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.choice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_given', models.DateField()),
                ('dose', models.CharField(blank=True, max_length=100, null=True)),
                ('next_dose_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='clients.client')),
                ('vaccine_name', models.ForeignKey(limit_choices_to={'category': 'vaccine_name'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.choice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='clientcareunit',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='check_clientcareunit_end_date_after_start'),
        ),
        migrations.AddConstraint(
            model_name='clientcareunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('client', 'unit'), name='uniq_active_client_unit_link'),
        ),
        migrations.AddConstraint(
            model_name='clientcareunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'PRIMARY')), fields=('client',), name='uniq_active_primary_unit_per_client'),
        ),
    ]
