# Generated by Django 6.0.7 on 2026-09-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosistype',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
