# Generated by Django 6.0.7 on 2026-10-09 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_full_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_routine_day_transfusion',
            field=models.BooleanField(default=False, help_text='If checked, automatically marks discharge upon recording transfusion completion.', verbose_name='Routine Day Transfusion (Day-Care)'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='date_of_admission',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='admission',
            name='date_of_discharge',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfusion',
            name='date_of_transfusion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
