# Generated by Django 6.0.7 on 2026-09-30 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_diagnosistype_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Laboratories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='laboratory_name',
        ),
        migrations.AddField(
            model_name='investigation',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='clients.laboratory'),
        ),
    ]
