# Generated by Django 6.0.7 on 2026-10-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_admission_is_routine_day_transfusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='diagnosis_details',
            field=models.CharField(blank=True, help_text='e.g. Genotype mutation (IVS1-5 G>C homozygous, Cd 41/42), or clinical variant notes', max_length=200, null=True, verbose_name='Diagnosis Details / Genotype'),
        ),
        migrations.CreateModel(
            name='ClientBMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_bmt', models.DateField(verbose_name='Date of BMT / HSCT')),
                ('is_successful', models.BooleanField(default=True, help_text='True if patient achieved sustained donor engraftment', verbose_name='Transplant Successful / Transfusion Free')),
                ('institution_name', models.CharField(max_length=200, verbose_name='Transplant Center / Hospital')),
                ('donor_type', models.CharField(blank=True, help_text='e.g. Matched Sibling (MSD), Matched Unrelated (MUD), Haploidentical', max_length=100, null=True, verbose_name='Donor Type')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmt_records', to='clients.client')),
            ],
            options={
                'verbose_name': 'Bone Marrow Transplant',
                'verbose_name_plural': 'Bone Marrow Transplants',
                'ordering': ['-date_of_bmt'],
            },
        ),
    ]
