# Generated by Django 6.0.7 on 2026-09-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_laboratory_remove_investigation_laboratory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationtype',
            name='recommended_interval_months',
            field=models.PositiveIntegerField(blank=True, help_text='Recommended test frequency in months (e.g. 1 = Monthly, 3 = Quarterly, 12 = Yearly)', null=True),
        ),
    ]
