# Generated by Django 6.0.7 on 2026-10-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_diagnosis_details_clientbmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbmt',
            name='date_of_bmt',
            field=models.DateField(blank=True, null=True, verbose_name='Date of BMT / HSCT'),
        ),
        migrations.AlterField(
            model_name='clientbmt',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Transplant Center / Hospital'),
        ),
        migrations.AlterField(
            model_name='clientdeath',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
