# Generated by Django 6.0.7 on 2026-10-10 06:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clientbmt_date_of_bmt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCareAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Assignment Start Date')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Assignment End Date')),
                ('notes', models.TextField(blank=True, help_text='e.g. Initial triage, Transitioned from Pediatrics', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='clients.thalassemiaunit')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='clients.client')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clients', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Doctor')),
            ],
            options={
                'verbose_name': 'Doctor Assignment',
                'verbose_name_plural': 'Doctor Assignments',
                'ordering': ['client', '-valid_from', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='check_assignment_valid_to_after_from'), models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('client', 'care_unit'), name='uniq_active_doctor_per_client_unit')],
            },
        ),
        migrations.CreateModel(
            name='DoctorCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Leave Start Date')),
                ('end_date', models.DateField(verbose_name='Leave End Date')),
                ('reason', models.CharField(blank=True, help_text='e.g. Annual Leave, Medical Leave, Conference', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Coverage Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absent_doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='leave_delegations', to=settings.AUTH_USER_MODEL, verbose_name='Doctor on Leave')),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_coverages', to='clients.thalassemiaunit')),
                ('covering_doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='covering_delegations', to=settings.AUTH_USER_MODEL, verbose_name='Covering Doctor')),
            ],
            options={
                'verbose_name': 'Doctor Leave Coverage',
                'verbose_name_plural': 'Doctor Leave Coverages',
                'ordering': ['-start_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='check_doctor_coverage_end_after_start')],
            },
        ),
    ]
